package(default_visibility = ["//visibility:public"])

cc_library(
    name = "route",
    hdrs = ["route.h"],
    deps = [
        "//homework6/map:map_lib",
        "//common/utils/file",
        "//common/proto:cc_route_proto",
        "@glog",
        "@gflags",
    ],
)